<script setup>
import {ref} from 'vue';
const modal=ref(false), plan=ref('Entrada individual · R$ 100'); const copied=ref(false);
function buy(p){plan.value=p;modal.value=true} function copyPix(){navigator.clipboard?.writeText('+55 11 98866-2162');copied.value=true;setTimeout(()=>copied.value=false,1800)}
</script>
<template>
<main>
<section class="poster" id="top"><img src="/chicha-fest-poster.png" alt="Chicha Fest — Saiko en São Paulo, viernes 18 de septiembre" /></section>
  <section class="intro"><div class="eyebrow">UNA NOCHE · DOS CULTURAS</div><h1>El barrio se<br><em>enciende.</em></h1><p>La primera edición de Chicha Fest llega a São Paulo con Saiko como invitado especial. Reggaetón, cumbia y una pista lista para cantar sin pausa.</p><div class="chips"><span>18 SEP</span><span>SÃO PAULO</span><span>7 PM</span></div></section>
  <section class="tickets"><div class="eyebrow">PRECIOS OFICIALES · SÃO PAULO</div><h2>Elige tu<br><em>entrada.</em></h2><div class="discount-banner"><span class="remesas-logo">remesas<span>.com</span></span><b>PREVENTA<br><strong>REMESAS</strong></b><small>Precio especial · cupos limitados</small></div><div class="price-board"><header><b>ZONAS</b><b>PREVENTA REMESAS</b><b>PRECIO FULL</b></header><div class="price-row"><i class="dot yellow"></i><strong>VIP</strong><span>R$ 190<sup>.00</sup></span><em>R$ 400<sup>.00</sup></em></div><div class="price-row"><i class="dot white"></i><strong>GENERAL</strong><span>R$ 150<sup>.00</sup></span><em>R$ 300<sup>.00</sup></em></div><button class="reserve-wide" @click="buy('Entrada VIP · R$ 190')">RESERVAR ENTRADA <span>↗</span></button></div><div class="vip-detail"><b>VIP INCLUYE</b><span>Acceso preferencial · mejor ubicación · experiencia exclusiva</span></div><div class="price-board boxes"><header><b>BOXES</b><b>PREVENTA REMESAS</b><b>PRECIO FULL</b></header><div class="price-row"><i class="dot green"></i><strong>BOX x5</strong><span>R$ 900<sup>.00</sup></span><em>R$ 2 000<sup>.00</sup></em></div><div class="price-row"><i class="dot green"></i><strong>BOX x10</strong><span>R$ 1 500<sup>.00</sup></span><em>R$ 3 000<sup>.00</sup></em></div><button class="reserve-wide" @click="buy('Box x5 · R$ 900')">CONSULTAR BOX <span>↗</span></button></div></section>
<section class="payment"><div class="eyebrow">PAGA POR PIX</div><h2>Directo a<br><em>la pista.</em></h2><p>Reserva, paga por PIX y mándanos tu comprobante. Te confirmamos por WhatsApp.</p><div class="pix"><small>PIX · VIELLO TORRES</small><b>+55 11 98866-2162</b><button @click="copyPix">{{copied?'¡COPIADO!':'COPIAR PIX'}}</button></div><a class="wa" href="https://wa.me/5511988662162" target="_blank">ENVIAR COMPROBANTE <span>↗</span></a></section>
<section class="music"><div class="eyebrow">SOUNDSYSTEM</div><h2>Saiko en<br><em>repeat.</em></h2><iframe title="Saiko en Spotify" src="https://open.spotify.com/embed/artist/1P7ibSNMQ2VTi5YDBvwBO1?utm_source=generator&theme=0" width="100%" height="352" frameBorder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe></section>
  <section class="final"><div class="eyebrow">NOS VEMOS EN LA PISTA</div><h2>Trae tu<br><em>propia energía.</em></h2><p>Chicha, neón y bajos fuertes. El resto lo ponemos nosotros.</p><button class="main-cta" @click="buy('Entrada individual · R$ 100')">COMPRAR ENTRADAS <span>↗</span></button><small>© 2026 VIELLO PRODUCCIONES</small></section>
  <button class="buy-dock" @click="buy('Entrada individual · R$ 100')">COMPRAR ENTRADAS <span>↗</span></button><a class="float-wa" href="https://wa.me/5511988662162" target="_blank" aria-label="WhatsApp">◔</a>
  <div v-if="modal" class="modal-wrap" @click.self="modal=false"><form class="modal" @submit.prevent="modal=false"><button type="button" class="x" @click="modal=false">×</button><div class="eyebrow">RESERVA · CHICHA FEST</div><h2>{{plan}}</h2><label>Nombre<input required placeholder="Tu nombre" /></label><label>WhatsApp<input required placeholder="+55 ..." /></label><label>Correo<input type="email" required placeholder="tu@email.com" /></label><button class="main-cta">CONTINUAR AL PAGO <span>↗</span></button></form></div>
</main></template>
