<script setup>
import {ref} from 'vue';
const modal=ref(false), plan=ref('Entrada individual · R$ 100'); const copied=ref(false);
function buy(p){plan.value=p;modal.value=true} function copyPix(){navigator.clipboard?.writeText('+55 11 98866-2162');copied.value=true;setTimeout(()=>copied.value=false,1800)}
</script>
<template>
<main>
<section class="poster" id="top"><div class="stars"></div><div class="poster-copy"><div class="sponsor">VIELLO PRODUÇÕES PRESENTA</div><div class="festival">CHICHA<br><span>FEST</span></div><div class="edition">1ª EDIÇÃO · BRASIL</div><p class="location">POR PRIMERA VEZ EN<br><b>SÃO PAULO</b></p><div class="artist">SAIKO</div><div class="date"><b>VIERNES<br><strong>18</strong></b><span>SEPTIEMBRE<br><i>7 PM</i></span></div><p class="venue">Discoteca Sabor Latino · São Paulo</p><button class="main-cta" @click="buy('Entrada individual · R$ 100')">COMPRAR ENTRADAS <span>↗</span></button></div><div class="poster-note">PREVENTA ABIERTA · CUPOS LIMITADOS</div></section>
  <section class="intro"><div class="eyebrow">UNA NOCHE · DOS CULTURAS</div><h1>El barrio se<br><em>enciende.</em></h1><p>La primera edición de Chicha Fest llega a São Paulo con Saiko como invitado especial. Reggaetón, cumbia y una pista lista para cantar sin pausa.</p><div class="chips"><span>18 SEP</span><span>SÃO PAULO</span><span>7 PM</span></div></section>
  <section class="tickets"><div class="eyebrow">PREVENTA · HASTA DOMINGO 13</div><h2>Elige tu<br><em>entrada.</em></h2><div class="cards"><article><small>EARLY BIRD</small><h3>Individual</h3><strong>R$ 100</strong><del>R$ 300 luego</del><button @click="buy('Entrada individual · R$ 100')">Reservar <span>↗</span></button></article><article class="gold"><small>PACK AMIGOS</small><h3>3 entradas</h3><strong>R$ 200</strong><del>R$ 500 luego</del><button @click="buy('Pack x3 entradas · R$ 200')">Reservar pack <span>↗</span></button></article></div></section>
<section class="payment"><div class="eyebrow">PAGA POR PIX</div><h2>Directo a<br><em>la pista.</em></h2><p>Reserva, paga por PIX y mándanos tu comprobante. Te confirmamos por WhatsApp.</p><div class="pix"><small>PIX · VIELLO TORRES</small><b>+55 11 98866-2162</b><button @click="copyPix">{{copied?'¡COPIADO!':'COPIAR PIX'}}</button></div><a class="wa" href="https://wa.me/5511988662162" target="_blank">ENVIAR COMPROBANTE <span>↗</span></a></section>
<section class="music"><div class="eyebrow">SOUNDSYSTEM</div><h2>Saiko en<br><em>repeat.</em></h2><iframe title="Saiko en Spotify" src="https://open.spotify.com/embed/artist/1P7ibSNMQ2VTi5YDBvwBO1?utm_source=generator&theme=0" width="100%" height="352" frameBorder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe></section>
  <section class="final"><div class="eyebrow">NOS VEMOS EN LA PISTA</div><h2>Trae tu<br><em>propia energía.</em></h2><p>Chicha, neón y bajos fuertes. El resto lo ponemos nosotros.</p><button class="main-cta" @click="buy('Entrada individual · R$ 100')">COMPRAR ENTRADAS <span>↗</span></button><small>© 2026 VIELLO PRODUCCIONES</small></section>
  <a class="float-buy" href="#tickets" @click.prevent="buy('Entrada individual · R$ 100')">COMPRAR<br><b>ENTRADAS</b><span>↗</span></a>
  <div v-if="modal" class="modal-wrap" @click.self="modal=false"><form class="modal" @submit.prevent="modal=false"><button type="button" class="x" @click="modal=false">×</button><div class="eyebrow">RESERVA · CHICHA FEST</div><h2>{{plan}}</h2><label>Nombre<input required placeholder="Tu nombre" /></label><label>WhatsApp<input required placeholder="+55 ..." /></label><label>Correo<input type="email" required placeholder="tu@email.com" /></label><button class="main-cta">CONTINUAR AL PAGO <span>↗</span></button></form></div>
</main></template>
